### ISSUE TITLE
Build fails on Ubuntu 21.10

### ISSUE THREAD

**Issue by robertgdev** [albertobsd/ecctools#5]
Trying to build on Ubuntu 21.10 (gcc 11.2.0) produces the following error: 

```
gcc -O3 -c bloom/bloom.c -o bloom.o
gcc -O3 -c sha256/sha256.c -o sha256.o
gcc -O3 -c base58/base58.c -o base58.o
gcc -O3 -c rmd160/rmd160.c -o rmd160.o
gcc -O3 -c xxhash/xxhash.c -o xxhash.o
gcc -O3 -c gmpecc.c -o gmpecc.o
gcc -O3 -c util.c -o util.o
gcc -O3 -o rehashaddress rehashaddress.c gmpecc.o util.o sha256.o base58.o rmd160.o -lgmp
/usr/bin/ld: gmpecc.o:(.bss+0x2020): multiple definition of `EC'; /tmp/ccEmWNB8.o:(.bss+0x2040): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x0): multiple definition of `DoublingG'; /tmp/ccEmWNB8.o:(.bss+0x20): first defined here
/usr/bin/ld: gmpecc.o:(.bss+0x2000): multiple definition of `G'; /tmp/ccEmWNB8.o:(.bss+0x2020): first defined here
collect2: error: ld returned 1 exit status
```

Any advice on how to fix this?

**Comment by albertobsd** [comment]
Install and use the gcc version 8.3.0
